export enum AreaOfInterest {
  CHEMISTRY = 'CHEMISTRY',
  COMMUNICATION = 'COMMUNICATION',
  COMPUTER_SCIENCE = 'COMPUTER_SCIENCE',
  CONSTRUCTION_AND_ARCHITECTURE = 'CONSTRUCTION_AND_ARCHITECTURE',
  ECONOMICS_AND_MANAGEMENT = 'ECONOMICS_AND_MANAGEMENT',
  EDUCATION = 'EDUCATION',
  ELECTRONICS = 'ELECTRONICS',
  ENGINEERING = 'ENGINEERING',
  ENTREPRENEURSHIP = 'ENTREPRENEURSHIP'
}
